### ISSUE TITLE
Support reading Chicago open TNC data

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gnss-ride-hailing-analyzer#3]
The City of Chicago has published open TNC data:
https://data.cityofchicago.org/Transportation/Transportation-Network-Providers-Trips/m6dm-c72p

We would like to be able to read that data into this application for processing.

For our purposes in Java, we don't need to read in the fields that have the geospatial `POINT` data like `POINT (-87.6333080367 41.899602111)`, because we can read in the raw lats and longs instead.

**Comment by BumbleFlash** [comment]
Issue resolved in #5
