### ISSUE TITLE
Add command-line parameter for input file

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gnss-ride-hailing-analyzer#4]
**Is your feature request related to a problem? Please describe.**
Currently the application had file names that are being parsed hard-coded into the application.

**Describe the solution you'd like**
We should add a command-line parameter for the input file name. We should assume that the file format will be the "bean" format for the Chicago data (see https://github.com/CUTR-at-USF/gnss-ride-hailing-analyzer/issues/3). So this can be implemented after https://github.com/CUTR-at-USF/gnss-ride-hailing-analyzer/issues/3.

**Comment by BumbleFlash** [comment]
Issue resolved in #5
